Start of receive-pack stream generator

diff --git a/geet-commit b/geet-commit
--- a/geet-commit
+++ b/geet-commit
@@ -1,23 +1,28 @@
 #!/bin/bash
 
+die() {
+    echo >&2 "$@"
+    exit 1
+}
+
 branch="$1"
 if [ $# -gt 1 ]; then
     repo="$($GEET-abspath $2)"
 else
     repo="$($GEET-git-remote)"
 fi
-parent="$($GEET-remote-head "$@")"
+#parent="$($GEET-remote-head "$@")"
+parent=398c54ff3645fc8aab9df36e39a5ad28befab04d
+test -n "$parent" || die "Couldn't find current remote head..."
+
 commitmsg="$(mktemp)"
 pack="$(mktemp)"
 trap "rm -f $commitmsg $pack" exit
 
-die() {
-    echo >&2 "$@"
-    exit 1
-}
-
 echo >"$commitmsg" "*** no commit message ***"
-vim "$commitmsg" || die "editor returned 1"
+#vim "$commitmsg" || die "editor returned 1"
 
-#$GEET-make-commit-pack "$branch" "$commitmsg" "$parent" |
+$GEET-ls-files -print0 |
+valgrind --error-exitcode=1 $GEET-make-commit-pack "$branch" "$commitmsg" "$parent" |
+hd
 #$GEET-rsh "$repo" git receive-pack .
